version: '3.8'

services:
  # HTTP Server dengan Caddy
  app:
    build:
      context: .
      target: http
      dockerfile: docker/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:-8.2}
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=production
      - APP_KEY=${APP_KEY:-base64:placeholder}
      - APP_DEBUG=false
      - APP_URL=http://localhost:8080
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-account_service}
      - DB_USERNAME=${DB_USERNAME:-laravel}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - CACHE_DRIVER=${CACHE_DRIVER:-database}
      - QUEUE_CONNECTION=${QUEUE_CONNECTION:-database}
      - SESSION_DRIVER=${SESSION_DRIVER:-database}
      # Redis (jika menggunakan cache redis)
      - REDIS_HOST=${REDIS_HOST:-}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      # AWS (jika menggunakan DynamoDB/SQS)
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-}
      - SQS_QUEUE=${SQS_QUEUE:-}
      - DYNAMODB_CACHE_TABLE=${DYNAMODB_CACHE_TABLE:-}
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/up"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Artisan service - bisa di-override dengan command apapun
  artisan:
    build:
      context: .
      target: artisan
      dockerfile: docker/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:-8.2}
    environment:
      - APP_ENV=production
      - APP_KEY=${APP_KEY:-base64:placeholder}
      - APP_DEBUG=false
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-account_service}
      - DB_USERNAME=${DB_USERNAME:-laravel}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - CACHE_DRIVER=${CACHE_DRIVER:-database}
      - QUEUE_CONNECTION=${QUEUE_CONNECTION:-database}
      - SESSION_DRIVER=${SESSION_DRIVER:-database}
      # Redis (jika menggunakan cache redis)
      - REDIS_HOST=${REDIS_HOST:-}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      # AWS (jika menggunakan DynamoDB/SQS)
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-}
      - SQS_QUEUE=${SQS_QUEUE:-}
      - DYNAMODB_CACHE_TABLE=${DYNAMODB_CACHE_TABLE:-}
    networks:
      - app-network
    # Default akan menjalankan "php artisan list"
    # Override dengan: docker-compose run artisan php artisan queue:work

networks:
  app-network:
    driver: bridge
