version: '3.8'

services:
  app:
    image: {{:docker_username}}/{{:docker_image_name}}:http-php8.2-latest
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - LOG_CHANNEL=stderr
      - LOG_LEVEL=warning
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/up"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  artisan:
    image: {{:docker_username}}/{{:docker_image_name}}:artisan-php8.2-latest
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - LOG_CHANNEL=stderr
      - LOG_LEVEL=warning
    # Override command untuk specific use case
    command: ["php", "artisan", "queue:work", "--verbose", "--tries=3", "--timeout=90"]
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
